### ISSUE TITLE
support for optional SARs

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/transforms#77]
NIAP wants the ability to define optional SARs for CC:2022 PPs, e.g. defining ALC_FLR.1 through .3 in PPs as strictly optional for CC users in the EU. The <a-component> tag currently does not have a status attribute to flag these as optional as <f-component>s do.

**Comment by robertmclemons** [comment]
The status attribute has been added to the ```<a-component>``` tag, but isn't used for anything yet.

**Comment by robertmclemons** [comment]
In XML PPs, optional SARs are indicated with status='optional' attribute. In the PP document, optional SARs appear in Appendix A.1 along with the Optional SFRs. 
In Modules, mandatory SARs are specified in the ```<mod-sars>``` section. Optional SARs, however, must be specified in the ```<opt-sfrs>``` section. It's very hard (maybe impossible) to do it a better way, and since it should be very rare, it's just not worth the effort. The 'optional' attribute is not used.
